name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dotnet-version: ['8.0'] # Add all your supported versions

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up .NET ${{ matrix.dotnet-version }}
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ matrix.dotnet-version }}

    - name: Restore dependencies
      run: dotnet restore

    - name: Build for ${{ matrix.dotnet-version }}
      run: dotnet build --configuration Release --framework net${{ matrix.dotnet-version }}

    - name: Publish for ${{ matrix.dotnet-version }}
      run: dotnet publish --configuration Release --framework net${{ matrix.dotnet-version }} -o publish-${{ matrix.dotnet-version }}

    - name: Upload artifact for ${{ matrix.dotnet-version }}
      uses: actions/upload-artifact@v4
      with:
        name: published-artifact-net${{ matrix.dotnet-version }}
        path: publish-${{ matrix.dotnet-version }}